### ISSUE TITLE
Allow Configuration of Settings through Environment Variables

### ISSUE THREAD

**Issue by rnikoopour** [RiotGames/cloud-inquisitor#121]
STS tokens only live for one hour and it is a pain point to have to swap out the config file every hour to have the latest values.

Would it be possible to grab configuration settings through the environment?

Desired precedence for configuration evaluation would be:
Env -> Settings Files -> Any other methods.

**Comment by bunjiboys** [comment]
This is how it already works. If you don't provide any keys at all, boto will resolve the credentials like normal. As per boto3's documentation (https://boto3.readthedocs.io/en/latest/guide/configuration.html):

1. Passing credentials as parameters in the boto.client() method
1. Passing credentials as parameters when creating a Session object
1. Environment variables
1. Shared credential file (~/.aws/credentials)
1. AWS config file (~/.aws/config)
1. Assume Role provider
1. Boto2 config file (/etc/boto.cfg and ~/.boto)
1. Instance metadata service on an Amazon EC2 instance that has an IAM role configured.
