### ISSUE TITLE
Rename variable ep to entry_point for better clarity

### ISSUE THREAD

**Issue by rnikoopour** [RiotGames/cloud-inquisitor#136]
This is an example code bit where `ep` is not immediately clear in it's meaning.

https://github.com/RiotGames/cloud-inquisitor/blob/e028e0ab9749b2d28c1e9d56f4d1ff3728a904fd/backend/cloud_inquisitor/plugins/commands/plugins.py#L26

I would change the `for ep in CINQ_PLUGINS['foo']['plugins']` to:

`for entry_point in CINQ_PLUGINS['foo']['plugins']`

**Comment by TheM0ng00se** [comment]
Fixed by Aretusa with #176
