### ISSUE TITLE
Event framework

### ISSUE THREAD

**Issue by markofu** [RiotGames/cloud-inquisitor#14]
Implement an event broadcast / listener framework that can be used to schedule tasks based on broadcasting of an event.

Example: When the EC2 collector has completed fetching information for an account/region, we can broadcast an even that would immediately trigger AWS Region based auditors to scan the account/region for issues.

**Comment by TheM0ng00se** [comment]
Hey @markofu , as part of the rework of the project this methodology will start being implemented in 2.1. I'm going to close this out and if there are aspects are missing please open another issue request.
