### ISSUE TITLE
New Tags Auditor Ignores "collect_only" boolean

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#171]
The new JSON configuration overrides collect_only if stop/remove stanzas are present.  This isn't a good thing clearly.  It looks like the logic is missing here: https://github.com/RiotGames/cinq-auditor-required-tags/blob/master/cinq_auditor_required_tags/__init__.py#L292

**Comment by tomvachon** [comment]
@markofu @zpritcha  any update on this issue?  its critical for us and I can even run the tool until its fixed

**Comment by zpritcha** [comment]
Hey @tomvachon -- sorry for the delay on this, I'll look into it shortly.

**Comment by tomvachon** [comment]
Thank you

**Comment by zpritcha** [comment]
@tomvachon https://github.com/RiotGames/cinq-auditor-required-tags/pull/33

This PR should resolve it, but I'd hold off on deploying until we test it a bit.

**Comment by laf-rge** [comment]
fixed!
