### ISSUE TITLE
Bug :  Required Tags Auditor : Can't terminate non-compliant instance due to Termination Protection

### ISSUE THREAD

**Issue by TheM0ng00se** [RiotGames/cloud-inquisitor#187]
The Required Tags Auditor may run into an issue such as:

An error occurred (OperationNotPermitted) when calling the Terminate
Instances operation: The instance 'xxxxxxxxxxxx' may not be terminated. Modify its 'disableApiTermination' instance attribute and try again.

The Required Tags Auditor needs to disable termination protection then kill the instance.

**Comment by rnikoopour** [comment]
Fixed in https://github.com/RiotGames/cloud-inquisitor/commit/cc48900cdde59928f6d0641628c42f97b923b2cf
