### ISSUE TITLE
Installation failing 

### ISSUE THREAD

**Issue by learn2project** [RiotGames/cloud-inquisitor#200]
error : 
  ami: sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON NOT NULL, \n\tad_group_base VARCHAR(64), \n\tenabled SMALLINT NOT NULL, \n\trequi' at line 6") [SQL: "\nCREATE TABLE accounts (\n\taccount_id INTEGER NOT NULL AUTO_INCREMENT, \n\taccount_name VARCHAR(64) NOT NULL, \n\taccount_number VARCHAR(12) NOT NULL, \n\taccount_type VARCHAR(50) NOT NULL DEFAULT 'AWS', \n\tcontacts JSON NOT NULL, \n\tad_group_base VARCHAR(64), \n\tenabled SMALLINT NOT NULL, \n\trequired_roles JSON, \n\tPRIMARY KEY (account_id), \n\tUNIQUE (account_name), \n\tUNIQUE (account_number)\n)\n\n"] (Background on this error at: http://sqlalche.me/e/f405)
==> ami: Terminating the source AWS instance...
==> ami: Cleaning up any extra volumes...
==> ami: No volumes to clean up, skipping
==> ami: Deleting temporary keypair...
Build 'ami' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> ami: Script exited with non-zero exit status: 1

_______________

 #uname -r
4.14.70-72.55.amzn2.x86_64

**Comment by HTTP500** [comment]
Hi, @learn2project , may I know what approach did you use to install this app?
Thanks!

**Comment by laf-rge** [comment]
bump! If we don't hear back we are going to close this issue.
