### ISSUE TITLE
Domain Hijacking auditor not resolving issues

### ISSUE THREAD

**Issue by TheM0ng00se** [RiotGames/cloud-inquisitor#206]
The domain hijacking auditor is displaying inconsistent results. 

- Some false positives have been observed
- In cases where the dangling DNS record is removed, the issue is not being removed

**Comment by TheM0ng00se** [comment]
This has been resolved by https://github.com/RiotGames/cinq-auditor-domain-hijacking/commit/03c78942cefde726bd5dc783597bd68af3068f56

where newer S3 URLs are not correctly handled.

**Comment by TheM0ng00se** [comment]
Closing

**Comment by TheM0ng00se** [comment]
.

**Comment by rnikoopour** [comment]
Closing

**Comment by zpritcha** [comment]
@rnikoopour
