### ISSUE TITLE
Project Docs Discrepancies

### ISSUE THREAD

**Issue by tyler-mast** [RiotGames/cloud-inquisitor#246]
## The readthedocs link in the description of the project is different than the link than the one in the main README.

The project description link leads to **cloud-inquisitor**.readthedocs.io (v1.0.2),
![Screen Shot 2019-03-21 at 11 35 53 AM](https://user-images.githubusercontent.com/42782633/54764329-eee6e900-4bcd-11e9-98d2-5b919397539c.png)

however the README link leads to **cloudinquisitor**.readthedocs.io (v3.0.0).
![Screen Shot 2019-03-21 at 11 36 03 AM](https://user-images.githubusercontent.com/42782633/54764498-4f762600-4bce-11e9-852b-e24f7cc6fb2d.png)

## Which of these is the officially supported docs?

I would naturally expect v3.0.0 to be the most recently updated set of docs, but it appears there is more content in the v1.0.2 docs.

**Comment by riot-jetaylor** [comment]
@tyler-mast we are reworking this project and will be reworking the docs with it.
