### ISSUE TITLE
docker build fail

### ISSUE THREAD

**Issue by chrjoh** [RiotGames/cloud-inquisitor#279]
## Summary
docker-compose build 
fails due to the this request can not be done as it looks like the domain do not exist anymore
http://releases.cloud-inquisitor.io/cinq-frontend-latest.tar.gz
Summary.

**Comment by riot-jetaylor** [comment]
@chrjoh we are moving on from the current design will likely not be supporting docker as we are moving to serverless.

Is there a use case you have for running this as a piece of continuously running infrastructure?

**Comment by chrjoh** [comment]
Hi, no was just testing and I use docker if available

**Comment by riot-jetaylor** [comment]
@chrjoh closing as we are moving most of the functionality to serverless.
