### ISSUE TITLE
Old Pip Install left in Packer Scripts

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#41]
https://github.com/RiotGames/cloud-inquisitor/blob/1.0.0/packer/scripts/install.sh#L41

Has an internal pip requirements install and blows up packer.  I have removed that line and all seems ok so far.  Was it just missed in the OSS process?

**Comment by tomvachon** [comment]
Its actually non-functional.  It seems like that file has dependancies which the release needs.  The local auth is completely missing.

Are all these bundled in since your local Pypi mirror isn't public (for good reason)

cinq-auditor-cloudtrail>=1.2.0
cinq-auditor-domain-hijacking>=1.1.1
cinq-auditor-ebs>=1.1.0
cinq-auditor-iam>=1.2.0
cinq-auditor-required-tags>=1.3.0
cinq-auditor-vpc-flowlogs>=1.2.0
cinq-collector-aws>=1.2.0
cinq-collector-dns>=1.3.3
cinq-scheduler-sqs>=1.4.0
cinq-standalone-scheduler>=1.3.0
cinq-auth-local>=1.2.0
cinq-auth-onelogin-saml>=1.1.

**Comment by tomvachon** [comment]
And upon further inspection, it seems that not everything is in PyPi public yet, so was this a pre-mature annoucenment on reddit?

**Comment by comerford** [comment]
Hey Tom, I believe we have released all these dependencies (see the other repos under RiotGames) and successfully had 3rd parties build and use prior to release, so likely just an oversight with the install script. Let me dig and get back to you.

**Comment by tomvachon** [comment]
I am spewing errors, If you can open up slack to non-admin signups, I'd be happy to collaborage on this

**Comment by tomvachon** [comment]
Here is what I got from PIP (it wasnt in the requirements file either)

cinq-auditor-cloudtrail (1.0.0)
cinq-auditor-domain-hijacking (1.0.0)
cinq-auditor-ebs (1.0.0)
cinq-auth-onelogin-saml (1.0.0)
cinq-collector-aws (1.0.0)
cinq-collector-dns (1.0.0)
cinq-scheduler-sqs (1.0.0)
cinq-scheduler-standalone (1.0.0)


That leaves these missing:
cinq-auditor-iam
cinq-auditor-required-tags
cinq-auditor-vpc-flowlogs
cinq-auth-local

**Comment by tomvachon** [comment]
I was able to get it started by building those 4 directly from source and pip installing the tar.gz directly.  So I think its just a matter of a couple requirements needed in PyPi and the requirements.txt being updated

**Comment by comerford** [comment]
Confirmed that I can't see those packages on pypi either. We'll get that sorted (and update the requirements and install script) to fix it. riot-plugins.txt is still referred to in the scheduler and API Docker files also

**Comment by tomvachon** [comment]
So, I got everything installed as I said, the last bit is the cinq-scheduler-sqs package just seems to be either setup wrong or referenced wrong.  

The logs are spewing: "Unable to locate the SQSScheduler scheduler plugin"

I showed it in the right place, just not working "/opt/pyenv/lib/python3.5/site-packages/cinq_scheduler_sqs"

**Comment by comerford** [comment]
Took a first whack at this:

https://github.com/RiotGames/cloud-inquisitor/pull/44

If we have an issue with SQS we should probably look to poke at that in a separate issue, but I still need to get the public pypi packages sorted out either way before we have a real solution.

**Comment by markofu** [comment]
On the `PyPi` issue, they were made public so let's dig into this on Slack with you.

**Comment by tomvachon** [comment]
Confirmed as fixed
