### ISSUE TITLE
Quickstart IAM Policy is incomplete for Target Account

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#42]
I am getting errors from CINQ listing buckets in the target account, it seems that the list isn't inclusive of all permissions required.

**Comment by tomvachon** [comment]
I'm compiling a list now

**Comment by tomvachon** [comment]
```
s3:List*
cloudfront:List*
route53:List* 
```
Are required which comes from https://github.com/RiotGames/cinq-collector-aws/blob/master/cinq_collector_aws/account.py on lines 31 to 33

**Comment by comerford** [comment]
I just checked a production version of this and you are correct, the role has the standard ReadOnly policy attached in addition to the one described in Quickstart (arn:aws:iam::aws:policy/ReadOnlyAccess)

**Comment by comerford** [comment]
I have merged https://github.com/RiotGames/cloud-inquisitor/pull/46 to address this. If it's still an issue after attaching ReadOnly, then please let me know

**Comment by markofu** [comment]
Closing for the minute as the core issue has been resolved.
