### ISSUE TITLE
Deleting Accounts Fails

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#43]
When deleting accounts through either the UI or manage.py

`Traceback (most recent call last):
  File "/opt/cinq-backend/cloud_inquisitor/plugins/commands/accounts.py", line 72, in run
    acct.delete()
AttributeError: 'Account' object has no attribute 'delete'`

**Comment by TheM0ng00se** [comment]
Yeah acct returns a class with no delete method, believe we should just be db.session.deleting and committing although need to ensure we're cleaning up any related data entries to the accounts.
