### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#49]
This is a list of the known documentation issues discovered in the debugging session:

1. SQS Queue documentation isn't present beyond the IAM setup.  FIFO queues are required but not documented anywhere.

2. Plugin usage/installation procedures are unclear

3. IAM policies are missing see #42 

Troubleshooting Docs:
1. Debug logging requires restart after being enabled
2. Documentation of manage.py routes (e.g. scheduler) would be useful for testing

**Comment by TheM0ng00se** [comment]
Correct that we are missing the SQS setup. 

Can you elaborate a little bit more on 2.?

**Comment by TheM0ng00se** [comment]
Nevermind...I see what you mean, the plugins themselves were previously installed through the build process and should normally be configured or tuned in the configuration section but they aren't there now by default..will fix this.

**Comment by markofu** [comment]
3. has been resolved by #42, which references attaching the `read-only` policy also.

**Comment by tomvachon** [comment]
Docs need to be added to include the need to log out and log in after accounts have been added.

**Comment by tomvachon** [comment]
Seems like debug logging has to be enabled in the UI and the log level moved to Debug, that might be revisited

**Comment by tomvachon** [comment]
Item is fixed by #57
