### ISSUE TITLE
Initial networking setup can lead to Packer SSH connection timeouts

### ISSUE THREAD

**Issue by znb** [RiotGames/cloud-inquisitor#52]
Unless you get the initial setup of the VPC, subnet etc. correct the Packer SSH connection will time out. 

This is something I battled with for a while.

Here's a Terraform script I used to create the required networking
https://github.com/znb/Cloud-Inquisitor-NetworkInit

Let me know if you need anything else.

**Comment by TheM0ng00se** [comment]
Yep thanks for this. I think we definitely can call this out more explicitly in the docs for requirements. We may want to link to a terraform build to help folks along in the future but figure most already have an environment for it.
