### ISSUE TITLE
AWS Regions file is blank

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#60]
On every new build the AWS regions file is empty.  It should be seeded with some regions (or even just 1 local region) and have a post-process job to refresh from the json ranges page

**Comment by markofu** [comment]
Seems to be failing for the first time on launch, but @tomvachon confirmed that a re-launch or restart of the `scheduler` results in the file being populated.

**Comment by TheM0ng00se** [comment]
During my testing I found that the regional collector would simply silently not run...I'll have a dig into this.

**Comment by TheM0ng00se** [comment]
@tomvachon : This should be fixed by #67 and #68 . Can you please confirm?

**Comment by markofu** [comment]
As per Tom's comment in Slack, this seems fixed so closing. Can reopen obviously.
