### ISSUE TITLE
Undefined names APP_DEBUG and APP_USE_USER_DATA

### ISSUE THREAD

**Issue by cclauss** [RiotGames/cloud-inquisitor#61]
Where are these two variables defined?  Are they environment variables that need to be accessed like: [os.getenv('APP_DEBUG', False)](https://docs.python.org/2/library/os.html#os.getenv)?

flake8 testing of https://github.com/RiotGames/cloud-inquisitor on Python 3.6.3

$ ___flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics___
```
./packer/files/backend-settings.py:10:9: F821 undefined name 'APP_DEBUG'
DEBUG = APP_DEBUG
        ^

./packer/files/backend-settings.py:13:17: F821 undefined name 'APP_USE_USER_DATA'
USE_USER_DATA = APP_USE_USER_DATA
                ^
```

**Comment by TheM0ng00se** [comment]
Hey @cclauss 

The APP_ are variables defined by packer. These end up getting configured into

/path/to/cinq-backend/settings/production.py

for enabling debug logging of the application and reading of instance UserData if you wish to use them.
