### ISSUE TITLE
Can't join Slack

### ISSUE THREAD

**Issue by 0xdabbad00** [RiotGames/cloud-inquisitor#73]
I think you need to set up one of those apps to setup user accounts for people, ex. https://streamalert.herokuapp.com/   I don't know how to join your slack otherwise, as it just prompts me with a username and password and no ability to create a user for your Slack.

**Comment by markofu** [comment]
Hey @0xdabbad00,

The `READMEs` have an auto-join [link](https://join.slack.com/t/cloud-inquisitor/shared_invite/enQtMjc1NTY5MTQ2MTAxLTA4MTM2NDBmNmY4ODRlMmNhNWQ4Yjk2ZWZhMmIyNWVkMDMzNjU5NWFhYzQ1YTZjNDNmY2M5MGI3OTdkNGE4Nzc), have you tried that?

I *think* you may be looking at the original `README`, which we updated shortly after open-sourcing.

Let me know how you get on.

m

**Comment by markofu** [comment]
So it looks like the `auto -join` is going to hit both a **max joins** and **time** limit, so we're going to look at something like this:

- https://github.com/ibratoev/aws-slackin

Please let me know if you can join in the meantime.

**Comment by 0xdabbad00** [comment]
I got in. I didn't see the new link.

**Comment by bunjiboys** [comment]
Closing this, as it was sorted
