### ISSUE TITLE
Enhance view of details through Config/CloudTrail

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#78]
As I find things which were not tagged correctly, I have to constantly go into AWS config to track the owner.  Since we present the email as the user name, it would be ideal to ingest that from CloudTrial and config to understand the root cause of a problem.

I understand you use the "Owner" tag for that, but we do not since we have the detail in CloudTrial and historical change in Config

**Comment by laf-rge** [comment]
I think this is out of scope. Feel free to continue the discussion if you disagree.
