### ISSUE TITLE
Email notification tracking

### ISSUE THREAD

**Issue by markofu** [RiotGames/cloud-inquisitor#9]
We would like to have a way to track if people have read the emails being sent by the auditors. The thought here is to use API gateways / lambda functions that will get accesses upon the email being loaded in the browser.

**Comment by TheM0ng00se** [comment]
With the improvement of #slack notification as well as emails we feel that this is enough. Also pixel-embedded email tracking feels out of the scope, plus certain devices preload these things. TL;DR it's not worth it at this time but we can revisit it later.
